--- #YAML:1.0
name:                Verby
version:             0.05
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Inspector:              0
    Directory::Scratch:            0
    File::Path:                    0
    File::Temp:                    0
    Hash::AsObject:                0
    List::MoreUtils:               0
    Log::Dispatch:                 2.21
    Moose:                         0.40
    MooseX::LogDispatch:           1.1001
    POE:                           0.37
    POE::Component::ResourcePool:  0.03
    Set::Object:                   1.17
    Test::Deep:                    0
    Test::Exception:               0
    Test::MockObject:              0
    Test::More:                    0
    Test::use::ok:                 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
